### ISSUE TITLE
[Bug]: Window Object Check Error in useLocalStorage Hook

### ISSUE THREAD

**Issue by kfahad5607** [typehero/typehero#1467]
### What happened?

**Description:**

Currently, the **useLocalStorage** hook (located in `apps/web/src/utils/useLocalStorage.ts`) checks for the existence of the `window` object directly. This results in an error during the compilation of the homepage:

![image](https://github.com/user-attachments/assets/55ea12cb-0b93-4661-8191-111f6b9f6f98)

**Proposed Solution:**
We can modify the check using `typeof` to verify if the `window` object is defined.
```typescript
if (typeof window !== 'undefined') {
  // Existing code
}
```

PS: I am happy to create a pull request for this if the issue is assigned to me. Thank you.

### What browsers are you seeing the problem on?

All

### Relevant log output

```zsh
web:dev: ReferenceError: window is not defined
web:dev:     at eval (webpack-internal:///(ssr)/./src/utils/useLocalStorage.ts:11:13)
web:dev:     at oT (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:12:68536)
web:dev:     at Object.useState (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:2078)
web:dev:     at t.useState (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:159634)
web:dev:     at useLocalStorage (webpack-internal:///(ssr)/./src/utils/useLocalStorage.ts:9:90)
web:dev:     at ProblemExplorerProvider (webpack-internal:///(ssr)/./src/app/problem-explorer.hooks.tsx:19:99)
web:dev:     at o7 (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6505)
web:dev:     at /var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11284
web:dev:     at ap (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
web:dev:     at ap (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42585)
web:dev:     at e (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:45795)
web:dev:     at ah (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:47773)
web:dev:     at ap (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:41224)
web:dev:     at e (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:45795)
web:dev:     at ah (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:47773)
web:dev:     at ac (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
web:dev:     at /var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014
web:dev:     at ap (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
web:dev:     at ap (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:42585)
web:dev:     at e (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:45795)
web:dev:     at ah (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:47773)
web:dev:     at e (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46110)
web:dev:     at ah (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:47773)
web:dev:     at /var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:53606
web:dev:     at /var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:54286
web:dev:     at ak (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:54294)
web:dev:     at Timeout._onTimeout (/var/tmp/personal-learnings/open-source/typehero/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:4037)
```

**Comment by bautistaaa** [comment]
the editor view is already client side rendered, this context should live close to the challenge view and it should just "work" I think
