### ISSUE TITLE
[Bug]: Client Exception error on undefined routes

### ISSUE THREAD

**Issue by urwah1248** [typehero/typehero#938]
### What happened?

If trying to access an undefined route.
### Expected Result
Redirects to 404 Page or render a 404 page.
### Actual Result
Throws a client exception error.
![Client Exception error screenshot](https://github.com/typehero/typehero/assets/107793187/8ff124e3-ccd4-4ccd-88cb-6556a0576af7)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```zsh
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76125)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76829)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76638)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76638)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76638)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76829)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76638)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76638)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76861)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76861)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76638)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76861)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76829)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76638)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76861)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76861)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76861)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76861)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76861)
    at vj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:75549)
    at wj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:76638)
    at Cj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:77726)
    at Dj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:78133)
    at Cj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:77875)
    at Dj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:78000)
    at Cj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:77875)
    at Dj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:78000)
    at Cj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:77875)
    at Dj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:78000)
    at Cj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:77875)
    at Dj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:78000)
    at Cj (https://typehero.dev/_next/static/chunks/8593596e-7d34da5ec2816916.js:9:77875)
```

**Comment by urwah1248** [comment]
I want to work on this issue as well.
So, please assign this issue to me.

**Comment by bautistaaa** [comment]
i actually just pushed a fix for this, sorry
